variable "vpc_cidr" {}
variable "client_name" {}
variable "ami" {}
variable "instance_type" {}
variable "subnet_id" {}
variable "public_subnet_cidr" {}
variable "public_subnet_az" {}
variable "private_subnet_cidr" {}
variable "private_subnet_az" {}
